name: Deploy (prod)

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    name: Build & Push images (web + bot) to GHCR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout репозитория
        uses: actions/checkout@v4

      - name: Логин в GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Настройка Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build & push WEB (prod)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile.web
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:web-sha-${{ github.sha }}
            ghcr.io/${{ github.repository }}:web-prod
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build & push BOT (prod)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile.bot
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:bot-sha-${{ github.sha }}
            ghcr.io/${{ github.repository }}:bot-prod
          cache-from: type=gha
          cache-to: type=gha,mode=max
