name: Deploy (staging)

on:
  push:
    branches: ["staging"]

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    name: Build & Push images (web + bot) to GHCR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout репозитория
        uses: actions/checkout@v4

      - name: Подготовка имени образа (lowercase для GHCR)
        run: |
          echo "IMAGE_REPO=ghcr.io/${GITHUB_REPOSITORY,,}" >> "$GITHUB_ENV"
          echo "Будем пушить в: $IMAGE_REPO"

      - name: Логин в GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Настройка Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build & push WEB (staging)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile.web
          push: true
          build-args: |
            GIT_SHA=${{ github.sha }}
          tags: |
            ${{ env.IMAGE_REPO }}:web-sha-${{ github.sha }}
            ${{ env.IMAGE_REPO }}:web-staging
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build & push BOT (staging)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile.bot
          push: true
          build-args: |
            GIT_SHA=${{ github.sha }}
          tags: |
            ${{ env.IMAGE_REPO }}:bot-sha-${{ github.sha }}
            ${{ env.IMAGE_REPO }}:bot-staging
          cache-from: type=gha
          cache-to: type=gha,mode=max
